# Generated by Django 4.1.5 on 2023-01-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_cartitem_price"),
        ("order", "0003_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="cart.cart",
            ),
        ),
    ]
