apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-store-deployment
  namespace: api-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-store
  template:
    metadata:
      labels:
        app: api-store
        version: diploma
    spec:
      containers:
      - name: api-store
        image: eu.gcr.io/${GCP_PROJECT}/api-store:${GITHUB_SHA}
        ports:
        - containerPort: 5050
        envFrom:
        - secretRef:
            name: api-store-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5