apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-store-deployment
  namespace: api-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-store
  template:
    metadata:
      labels:
        app: api-store
        version: diploma
    spec:
      containers:
      - name: api-store
        image: gcr.io/PROJECT_ID/api-store:latest
        ports:
        - containerPort: 5050
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres:5432/api_store"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 15
          periodSeconds: 15
