apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-store-deployment
  namespace: api-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-store
  template:
    metadata:
      labels:
        app: api-store
    spec:
      containers:
      - name: api-store
        image: eu.gcr.io/${GCP_PROJECT}/api-store:${GITHUB_SHA}
        ports:
        - containerPort: 5050
        envFrom:
        - secretRef:
            name: api-store-secret