apiVersion: v1
kind: Service
metadata:
  name: api-store-service
  namespace: api-store
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5050
    protocol: TCP
  selector:
    app: api-store
