apiVersion: v1
kind: Service
metadata:
  name: bookshop-service
  namespace: bookshop
spec:
  type: LoadBalancer
  selector:
    app: bookshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000