apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-deployment
  namespace: bookshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop
  template:
    metadata:
      labels:
        app: bookshop
        version: diploma
    spec:
      containers:
      - name: bookshop
        image: gcr.io/PROJECT_ID/bookshop:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres:5432/bookshop"
        - name: API_STORE_URL
          value: "http://api-store-service.api-store.svc.cluster.local"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 15
