apiVersion: v1
kind: Secret
metadata:
  name: bookshop-secret
  namespace: bookshop
stringData:
  DATABASE_URL: "postgres://${DB_BOOKSHOP_USER}:${DB_BOOKSHOP_PASSWORD}@${DB_BOOKSHOP_HOST}:${DB_BOOKSHOP_PORT}/${DB_BOOKSHOP_NAME}"