apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-deployment
  namespace: bookshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshop
  template:
    metadata:
      labels:
        app: bookshop
        version: diploma
    spec:
      containers:
      - name: bookshop
        image: eu.gcr.io/${GCP_PROJECT}/bookshop:${GITHUB_SHA}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bookshop-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10