apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # Bookshop upstream
        upstream bookshop {
            server bookshop-service.bookshop-prod.svc.cluster.local:5000;
        }
        
        # API Store upstream
        upstream apistore {
            server api-store-service.api-store-prod.svc.cluster.local:5050;
        }
        
        server {
            listen 80;
            server_name _;
            
            # Root redirect to bookshop
            location = / {
                proxy_pass http://bookshop/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # Bookshop frontend routes
            location ~ ^/(shop|bookshop|frontend|web|html|ui)/?$ {
                proxy_pass http://bookshop/frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # Analytics/API Store frontend routes
            location ~ ^/(analytics|dashboard|api-store)/?$ {
                proxy_pass http://apistore/frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # Bookshop API routes
            location /api/ {
                proxy_pass http://bookshop/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # API Store routes
            location /purchases {
                proxy_pass http://apistore/purchases;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /most-popular-day {
                proxy_pass http://apistore/most-popular-day;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # Health checks
            location /health {
                proxy_pass http://bookshop/health;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            # API documentation
            location /docs {
                proxy_pass http://apistore/docs;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: default
  labels:
    app: nginx-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-proxy-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-proxy 