apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream cloud_storage {
            server storage.googleapis.com:443;
        }
        
        server {
            listen 80;
            server_name _;
            
            # Main frontend - redirect to bookshop
            location / {
                return 301 /bookshop;
            }
            
            # Bookshop frontend
            location /bookshop {
                proxy_pass https://storage.googleapis.com/diploma-static-prod-645ba250/bookshop-frontend.html;
                proxy_set_header Host storage.googleapis.com;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_ssl_server_name on;
                proxy_ssl_verify off;
            }
            
            # API Store frontend
            location /api-store {
                proxy_pass https://storage.googleapis.com/diploma-static-prod-645ba250/api-store-frontend.html;
                proxy_set_header Host storage.googleapis.com;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_ssl_server_name on;
                proxy_ssl_verify off;
            }
            
            # Health check
            location /health {
                return 200 "Frontend Proxy OK\n";
                add_header Content-Type text/plain;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-proxy
  template:
    metadata:
      labels:
        app: frontend-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy-service
  namespace: default
spec:
  selector:
    app: frontend-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 