# TLS Certificates Configuration for DuckDNS domains
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lexagorbenko@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-store-tls
  namespace: api-store-prod
spec:
  secretName: api-store-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api-diploma-project.duckdns.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookshop-tls
  namespace: bookshop-prod
spec:
  secretName: bookshop-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - bookshop-diploma-project.duckdns.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: diploma-project-tls
  namespace: default
spec:
  secretName: diploma-project-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - diploma-project.duckdns.org
---
# Ingress for API Store with TLS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-store-ingress
  namespace: api-store-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api-diploma-project.duckdns.org
    secretName: api-store-tls
  rules:
  - host: api-diploma-project.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-store-service
            port:
              number: 80
---
# Ingress for Bookshop with TLS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshop-ingress
  namespace: bookshop-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - bookshop-diploma-project.duckdns.org
    secretName: bookshop-tls
  rules:
  - host: bookshop-diploma-project.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bookshop-service
            port:
              number: 80 