# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: bookshop
    restart: always
    environment:
      POSTGRES_PASSWORD: 'dbpass'
      POSTGRES_USER: 'aliaksei'
      POSTGRES_DB: bookshop
      PGDATA: /Users/aliaksei/PycharmProjects/bookshop/postgres/data
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
