# Generated by Django 4.1.5 on 2023-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="state",
            field=models.CharField(
                choices=[("N", "Новая"), ("U", "Б.У.")], default="N", max_length=2
            ),
        ),
    ]
