# Generated by Django 4.1.5 on 2023-01-18 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_cartitem_price"),
        ("books", "0002_alter_book_state"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookInstances",
            new_name="BookInstance",
        ),
    ]
