# Generated by Django 4.1.5 on 2023-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
