# Generated by Django 4.1.5 on 2023-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_cartitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
    ]
