# Generated by Django 4.1.5 on 2023-01-19 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="quantity",
            new_name="count",
        ),
    ]
